### ISSUE TITLE
Setup plugin

### ISSUE THREAD

**Issue by SbiCA** [ravendb/ravendb-grafana-datasource#3]
Hi @ml054 

I was wondering what's the best way to setup the plugin.

I was able to build it from source and follow the granafa docs to register it but I'm not sure if this would be what someone new to the topic would come up with
https://grafana.com/tutorials/build-a-data-source-plugin/#set-up-your-environment

I think there are two paper cuts that should be added here
1. how to get the public private key from pfx (since that's what you get from raven cloud by default) 
2. how to setup a "local" unsecure connection

In addition once it's published to official store I think it would be good to have some docs around how to get it installed with grafana-cli/ docker

Cheers
Simon

**Comment by ml054** [comment]
Hi @SbiCA,

I really appreciate your feedback. 

You can find some basic information here: https://github.com/ravendb/ravendb-grafana-datasource#set-ravendb-as-your-data-source

However we rework that section to be easier to setup - grafana uses generic component for http/https connections and most of those fields are not relevant. 

You can track progress here: 
https://issues.hibernatingrhinos.com/issue/RavenDB-18304

Steps:
- enable TLS Client Auth
- provide key and certificate - you can find them in certificates zip downloaded from cloud portal
- optionally provide CA certificate 
- you can click on 'test' connection button 

@SbiCA Could you also clarify part related to `grafana-cli/docker` setup?

**Comment by SbiCA** [comment]
Sure I was referring to something like this 

How to get started from source (locally)

1. yarn build
2. docker-compose up
``` docker-compose
version: '3.0'

services: 
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=ravendb-datasource"
    volumes:
      - ./dist:/var/lib/grafana/plugins
```
see https://github.com/grafana/grafana/issues/31125

how to get started once published to market place
``` docker-compose
version: '3.0'

services: 
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - "GF_INSTALL_PLUGINS =ravendb-datasource 1.0.0"
```
see https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container

**Comment by ml054** [comment]
@SbiCA 

Description was updated in https://github.com/ravendb/ravendb-grafana-datasource/pull/4

For docker related stuff I opened issue: https://issues.hibernatingrhinos.com/issue/RavenDB-18323

So closing this one.
